### ISSUE TITLE
Convert to Current Swift Syntax?

### ISSUE THREAD

**Issue by kakaxicm** [o0starshine0o/iOS-ArtSignProDemoOC#1]
The project “Pods” has targets that contain source code developed with an earlier version of Swift.

Choose “Convert” to update the source code in this project to the latest SDKs. You will be given the choice to use Swift 2.3 syntax or update to Swift 3.

This action can be performed later using “Convert to Current Swift Syntax” in the Edit menu.

**Comment by o0starshine0o** [comment]
![-1](https://cloud.githubusercontent.com/assets/6480059/21003119/8ec8b16a-bd64-11e6-82c0-f0a151fed872.jpg)
follow these steps , you can fix the errors
